name: Push a new image after a new release has been made
on:
  push:
    tags:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        if: startsWith( github.ref, 'refs/tags/') == true || startsWith(github.ref, 'refs/heads/master') == true
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build/push
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          # DOCKER_ORGNAME: define DOCKER_ORGNAME secret to push to organization namespace that DOCKER_USERNAME has access to
          DOCKER_ORGNAME: ${{ secrets.DOCKER_ORGNAME }}
          # DOCKER_REPO_NAME:
        run: bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/master/git_action.sh)
        shell: bash
